require 'edmunds/api'
require 'edmunds/photo'
require 'edmunds/make'
require 'edmunds/model'
require 'edmunds/model_year'
require 'edmunds/style'
require 'edmunds/value'

require 'edmunds/equipment'

require 'edmunds/cost_to_own'
require 'edmunds/edmunds_ratings'
require 'edmunds/incentives'
require 'edmunds/maintenance'
require 'edmunds/market_value'
require 'edmunds/vehicle_ratings'
require 'edmunds/vin'
